import DataTableCompo from 'c/dataTableCompo';

describe('c-data-table-compo', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {

        const element = createElement('c-data-table-compo', {
            is: DataTableCompo
        });
        document.body.appendChild(element);
        expect(1).toBe(1);
    });
});