import MyFirstLwcComp from 'c/myFirstLwcComp';

describe('c-my-first-lwc-comp', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-my-first-lwc-comp', {
            is: MyFirstLwcComp
        });
        document.body.appendChild(element);
        expect(1).toBe(1);
    });
});