
import CarLoan from 'c/carLoan';

describe('c-car-loan', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-car-loan', {
            is: CarLoan
        });
        document.body.appendChild(element);
        expect(1).toBe(1);
    });
});