import ApplicationFormComponent from 'c/applicationFormComponent';

describe('c-application-form-component', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-application-form-component', {
            is: ApplicationFormComponent
        });
        document.body.appendChild(element);
        expect(1).toBe(1);
    });
});