import AccountTableCompo from 'c/accountTableCompo';

describe('c-account-table-compo', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-account-table-compo', {
            is: AccountTableCompo
        });
        document.body.appendChild(element);

        expect(1).toBe(1);
    });
});