import ModelPublisherCompo from 'c/modelPublisherCompo';

describe('c-model-publisher-compo', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-model-publisher-compo', {
            is: ModelPublisherCompo
        });
        document.body.appendChild(element);
        expect(1).toBe(1);
    });
});