import SearchAccount from 'c/searchAccount';

describe('c-search-account', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-search-account', {
            is: SearchAccount
        });
        document.body.appendChild(element);

        expect(1).toBe(1);
    });
});