import LoadAccRecords from 'c/loadAccRecords';

describe('c-load-acc-records', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-load-acc-records', {
            is: LoadAccRecords
        });
        document.body.appendChild(element);
        expect(1).toBe(1);
    });
});